### ISSUE TITLE
Class Http not Found

### ISSUE THREAD

**Issue by gobackdev** [larasocket/larasocket-driver#1]
Hi. I use you package. But while executing the request, I get the error

message | "Class 'Http' not found"
-- | --
exception | "Error"
file | "/vendor/larasocket/larasocket-driver/src/LarasocketBroadcaster.php"
line | 139

I think you are using the wrong class. Nessesary to use \Illuminate\Support\Facades\Http

**Comment by exzachlyvv** [comment]
Fixed in 1.0.3
